on: [push]

name: VM_autocheck

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Azure CLI script file
      uses: azure/CLI@v1
      env:
        SECRET_PRINCIPAL_ID: ${{ secrets.SECRET_PRINCIPAL_ID }}
        SECRET_PRINCIPAL_PW: ${{ secrets.SECRET_PRINCIPAL_PW }}
        SECRET_PRINCIPAL_TENANT: ${{ secrets.SECRET_PRINCIPAL_TENANT }}
        VAULT_NAME: ${{ secrets.VAULT_NAME }}
      with:
        azcliversion: 2.30.0
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/vm_check.sh
          $GITHUB_WORKSPACE/vm_check.sh

    - name: Setup Git
      run: |
        git config --global user.email "github-action@github.com"
        git config --global user.name "GitHub Action"

    - name: Commit and Push CSV file
      run: |
        git add customer_vms.csv
        git commit -m "Update customer_vms.csv"
        git push
